name: Test Install, New Script, Run Script

on: [pull_request, workflow_dispatch]

jobs:
  install:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
      - name: Extract Branch Name
        uses: rlespinasse/github-slug-action@3.1.0

      - name: Print event variables
        run: |
          echo "url: ${{ github.event.pull_request.url }}"

      - name: Print slug/short variables
        run: |
          echo "Slug variables"
          echo "   ref        : ${{ env.GITHUB_REF_SLUG }}"
          echo "   head ref   : ${{ env.GITHUB_HEAD_REF_SLUG }}"
          echo "   base ref   : ${{ env.GITHUB_BASE_REF_SLUG }}"
          echo "   event ref  : ${{ env.GITHUB_EVENT_REF_SLUG }}"
          echo "   repository : ${{ env.GITHUB_REPOSITORY_SLUG }}"
          echo "Slug URL variables"
          echo "   ref        : ${{ env.GITHUB_REF_SLUG_URL }}"
          echo "   head ref   : ${{ env.GITHUB_HEAD_REF_SLUG_URL }}"
          echo "   base ref   : ${{ env.GITHUB_BASE_REF_SLUG_URL }}"
          echo "   event ref  : ${{ env.GITHUB_EVENT_REF_SLUG_URL }}"
          echo "   repository : ${{ env.GITHUB_REPOSITORY_SLUG_URL }}"
          echo "Short SHA variables"
          echo "   sha        : ${{ env.GITHUB_SHA_SHORT }}"
          echo "PR variables"
          echo "   pr head sha: ${{ env.GITHUB_EVENT_PULL_REQUEST_HEAD_SHA_SHORT }}"
          echo "   pr event ref: ${{ env.GITHUB_EVENT_REF_SLUG_URL }}"

      - name: Log Ref Name
        run: echo "Running install from ${{ env.GITHUB_REF_SLUG }}"

      - name: Clone kit
        run: |
          git clone ${{ github.event.pull_request.head.repo.clone_url }} ~/.kit
          ls ~/.kit

      - name: Checkout to ref - ${{ github.event.pull_request.head.sha }}
        run: |
          cd ~/.kit
          git checkout ${{ github.event.pull_request.head.sha }}

      - name: Install latest node
        run: >
          bash ~/.kit/install-node.sh --prefix ~/.kit/node

      - name: npm install
        run: |
          cd ~/.kit
          ~/.kit/node/bin/npm install

      - name: cat kit.sh
        run: cat ~/.kit/script

      - name: clone ~/.kenv dir
        run: git clone https://github.com/johnlindquist/kenv.git ~/.kenv

      - name: setup .kenv dir
        run: |
          cd ~/.kit
          KENV=~/.kenv bash ./script ./setup/setup.js

      - name: list .kenv dir
        run: >
          ls ~/.kenv

      - name: View .profile
        run: >
          cat ~/.profile

      - name: View bin
        run: >
          cat ~/.kit/bin/kit

      - name: View .env
        run: >
          cat ~/.kenv/.env

      - name: Adding ~/.kit/bin to Path
        run: echo "~/.kit/bin" >> $GITHUB_PATH

      - name: Adding ~/.kenv/bin to Path
        run: echo "~/.kenv/bin" >> $GITHUB_PATH

      - name: Chmod ~/.kit/bin/kit
        run: chmod +x ~/.kit/bin/kit

      - name: Create a Test Script
        run: >
          kit new running-test-template --template default

      - name: Run the Test Script
        run: >
          running-test-template --trust

      - name: Test kit script with new-and-rm
        run: |
          KENV=~/.kenv KIT_TEMPLATE=default ~/.kit/script ~/.kit/test/new-and-rm.js
