name: Test Install, New Script, Run Script

on: [pull_request, workflow_dispatch]

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - name: Extract Branch Name
        uses: rlespinasse/github-slug-action@3.1.0

      - name: Print slug/short variables
        run: |
          echo "Slug variables"
          echo "   ref        : ${{ env.GITHUB_REF_SLUG }}"
          echo "   head ref   : ${{ env.GITHUB_HEAD_REF_SLUG }}"
          echo "   base ref   : ${{ env.GITHUB_BASE_REF_SLUG }}"
          echo "   event ref  : ${{ env.GITHUB_EVENT_REF_SLUG }}"
          echo "   repository : ${{ env.GITHUB_REPOSITORY_SLUG }}"
          echo "Slug URL variables"
          echo "   ref        : ${{ env.GITHUB_REF_SLUG_URL }}"
          echo "   head ref   : ${{ env.GITHUB_HEAD_REF_SLUG_URL }}"
          echo "   base ref   : ${{ env.GITHUB_BASE_REF_SLUG_URL }}"
          echo "   event ref  : ${{ env.GITHUB_EVENT_REF_SLUG_URL }}"
          echo "   repository : ${{ env.GITHUB_REPOSITORY_SLUG_URL }}"
          echo "Short SHA variables"
          echo "   sha        : ${{ env.GITHUB_SHA_SHORT }}"

      - name: Log Branch Name
        run: echo "Running install from ${{ env.GITHUB_HEAD_REF_SLUG }}"

      - name: Clone kit
        run: |
          git clone https://github.com/johnlindquist/kit.git ~/.kit
          ls ~/.kit

      - name: Checkout to branch - ${{ env.GITHUB_HEAD_REF_SLUG }}
        run: |
          cd ~/.kit
          git checkout ${{ env.GITHUB_HEAD_REF_SLUG }}

      - name: Install latest node
        run: >
          bash ~/.kit/setup/install-node.sh --prefix ~/.kit/node

      - name: npm install
        run: |
          cd ~/.kit
          ~/.kit/node/bin/npm install

      - name: cat kit.sh
        run: cat ~/.kit/script

      - name: setup .kenv dir
        run: |
          cd ~/.kit
          KENV=~/.kenv bash ./script ./setup/setup.js

      - name: list .kenv dir
        run: >
          ls ~/.kenv

      - name: View .profile
        run: >
          cat ~/.profile

      - name: View bin
        run: >
          cat ~/.kenv/bin/new

      - name: View .env
        run: >
          cat ~/.kenv/.env

      - name: Adding sk to Path
        run: echo "~/.kenv/bin" >> $GITHUB_PATH

      - name: Create a Test Script
        run: >
          new running-test-template --template test

      - name: Run the Test Script
        run: >
          running-test-template --trust

      - name: Test new-and-rm
        run: |
          cd ~/.kenv
          KENV=. KIT_TEMPLATE=default kit/script kit/test/new-and-rm.js
